# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdc_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.CharField(max_length=128),
        ),
    ]
