# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdc_module', '0002_auto_20180726_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='attach_volume_id',
        ),
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
