# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(default=None)),
                ('ram', models.BigIntegerField(default=None)),
                ('disk', models.BigIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(default=None, max_length=500)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Rights')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_VDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='VDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(default=None)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota')),
            ],
        ),
        migrations.AddField(
            model_name='user_vdc',
            name='vdc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.VDC'),
        ),
        migrations.AlterUniqueTogether(
            name='user_vdc',
            unique_together=set([('user', 'vdc')]),
        ),
        migrations.AlterUniqueTogether(
            name='user_role',
            unique_together=set([('user', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='user_quota',
            unique_together=set([('user', 'quota')]),
        ),
        migrations.AlterUniqueTogether(
            name='role_rights',
            unique_together=set([('role', 'right')]),
        ),
    ]
