# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20180709_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdc',
            name='backend_info',
            field=models.TextField(blank=True, default=None),
        ),
    ]
