# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20180710_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_use_VDC',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
