# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_auto_20180711_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(default=None)),
                ('ram', models.BigIntegerField(default=None)),
                ('volume', models.BigIntegerField(default=None)),
                ('instances', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user_quota',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='user_quota',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='user_quota',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota'),
        ),
        migrations.AlterField(
            model_name='vdc',
            name='quota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota'),
        ),
        migrations.DeleteModel(
            name='User_Quota',
        ),
        migrations.AddField(
            model_name='user',
            name='usage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
        migrations.AddField(
            model_name='vdc',
            name='usage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
    ]
