# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20180710_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='cpu',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='disk',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='ram',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vdc',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
