# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20180711_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
        migrations.AlterField(
            model_name='vdc',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota'),
        ),
        migrations.AlterField(
            model_name='vdc',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
    ]
