# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_user_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Quota'),
        ),
    ]
