# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20180711_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
        migrations.AlterField(
            model_name='vdc',
            name='usage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Usage'),
        ),
    ]
