# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_remove_user_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quota',
        ),
    ]
