# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-14 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_auto_20180710_0800'),
        ('user_auth', '0016_remove_user_quota'),
    ]

    operations = [
    ]
