# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0019_auto_20180724_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpu',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='instances',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='ram',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='volume',
            field=models.IntegerField(default=None),
        ),
    ]
