# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_auto_20180724_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdc',
            name='cpu',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='vdc',
            name='instances',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='vdc',
            name='ram',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='vdc',
            name='volume',
            field=models.IntegerField(default=None),
        ),
    ]
